### ISSUE TITLE
How to log response query

### ISSUE THREAD

**Issue by bachlx19992** [gdnsd/gdnsd#222] opened 2022-07-06 06:48 UTC
I want to get the log response query of gdns like log query of bind
Such as: 06-Jul-2022 13:47:29.788 queries: info: client 172.15.0.17#49392 (adservice.google.com): query: adservice.google.com IN A + (172.15.0.45)

So what do I need to do?
Thank a lot

**Comment by astrolox** [comment] 2022-07-06 17:25
I used #215 to send all the queries and responses to another process which then does appropriate logging, statistics generation, etc.

**Comment by bachlx19992** [comment] 2022-07-07 07:53
> I used #215 to send all the queries and responses to another process which then does appropriate logging, statistics generation, etc.

I see that dnstap doesn't support gdns, is that correct?
http://dnstap.info/

**Comment by astrolox** [comment] 2022-07-07 09:11
It's the other way around.
gdnsd has to support dnstap.
The pull request I linked above adds that support. It just hasn't been merged yet.
It's working well in production for me.

**Comment by bachlx19992** [comment] 2022-07-07 09:18
pls guide me to integrate dnstap with gdns
I still haven't figured out how
Thank you very much

**Comment by bachlx19992** [comment] 2022-07-08 02:48
> It's the other way around. gdnsd has to support dnstap. The pull request I linked above adds that support. It just hasn't been merged yet. It's working well in production for me.

can you merge it now?
i need to config gdns ASAP

**Comment by astrolox** [comment] 2022-07-09 13:31
Hi, 

You can easily find the code in the pull request and build it yourself. e.g. by following [this guide in the github documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally)

If you need assistance with that, I suggest looking at bringing a freelance developer on to your team.

As for merging it ... this isn't my project, so that's not my call.

**Comment by bachlx19992** [comment] 2022-07-25 07:05
@astrolox I found commit at https://github.com/tiggee-tech/gdnsd/tree/dnstap_support
I downloaded this source code and installed it but it didn't work
When I run make check j -4, it show error no such file or directory : dnstap.pb-c.c and dnstap.pb-c.h
I already install libprotobuf-c, libfstrm
can you help me fix it? 

[root@gdns gdnsd-dnstap_support]# make check -j 4
Making check in .
make[1]: Entering directory `/usr/src/gdnsd-dnstap_support'
  GEN      src/dnstap.pb-c.c
  CC       src/src_gdnsd-dnstap.o
  CC       src/src_gdnsd-main.o
  CC       src/src_gdnsd-cookie.o
dnstap.proto: No such file or directory
make[1]: *** [src/dnstap.pb-c.c] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from src/dnstap.c:3:0:
src/dnstap.h:3:25: fatal error: dnstap.pb-c.h: No such file or directory
 #include "dnstap.pb-c.h"
                         ^
compilation terminated.
make[1]: *** [src/src_gdnsd-dnstap.o] Error 1
In file included from src/main.c:37:0:
src/dnstap.h:3:25: fatal error: dnstap.pb-c.h: No such file or directory
 #include "dnstap.pb-c.h"
                         ^
compilation terminated.
make[1]: *** [src/src_gdnsd-main.o] Error 1
make[1]: Leaving directory `/usr/src/gdnsd-dnstap_support'
make: *** [check-recursive] Error 1

**Comment by sheepbrew** [comment] 2022-08-25 08:28
@bachlx19992 For our environment, what I did to workaround this was to put dnsdist (which supports dnstap) in front of gdnsd, and then make use the EDNS Client Subnet feature to forward the source IP to gdnsd.

Great work @astrolox ! I hope your PR gets accepted so I can make my deployment much simpler.

**Comment by blblack** [comment] 2024-01-03 23:28
Closing old stale issues (feel free to re-open if it floats your boat!) (also, basically dupe of #215 )

**Closed by blblack** 2024-01-03 23:28 UTC
